TEST_HELPER_SOURCES := test_status.c
TEST_HELPER_OBJECTS := $(patsubst %.c,%.o,$(TEST_HELPER_SOURCES))

CFLAGS += $(ISP_CFLAGS)
INCLUDES += $(ISP_INCLUDES)
INCLUDES += -I.
LDFLAGS += $(ISP_LDFLAGS)

TARGET := $(patsubst %,$(OUTPUT_DIR)/%,$(TEST))
SOURCE := $(patsubst %,%.c,$(TEST))

all: $(TARGET)

$(TARGET): $(ISP_OBJECTS) $(ISP_LIBS) $(ISP_DEPS) $(TEST_HELPER_OBJECTS)
	$(CC) $(CFLAGS) $(INCLUDES) $(ISP_OBJECTS) $(TEST_HELPER_OBJECTS) \
		$(SOURCE) $(ISP_LIBS) -o $@ $(LDFLAGS)

$(TEST_HELPER_OBJECTS): %.o: %.c $(TEST_HELPER_SOURCES)
	$(CC) $(CFLAGS) $(INCLUDES) $< -c -o $@
