
CFLAGS := -O2 -fno-common -funroll-loops -finline-functions --param max-inline-insns-auto=20 -falign-functions=4 -falign-jumps=4 -falign-loops=4
CFLAGS += -DFLAGS_STR=\""$(CFLAGS)"\"

#XXX: hard-coding while debugging
#CFLAGS += -DITERATIONS=10000 -DPERFORMANCE_RUN=1
CFLAGS += -DITERATIONS=1 -DPERFORMANCE_RUN=1
