#!/bin/bash

apt-get update

apt-get install -y \
        cmake \
        locales \
        locales-all \
        make \
        python \
        python2.7 \
        python3 \
        python3-pip \
        python-pip \
        python-pytest \
        python3-pytest

pip2 install pytest-timeout
pip3 install pyelftools pyyaml pytest-timeout
